ALTER TABLE job_templates
    ADD COLUMN IF NOT EXISTS git_url TEXT,
    ADD COLUMN IF NOT EXISTS git_ref TEXT NOT NULL DEFAULT 'main';

ALTER TABLE jobs
    ADD COLUMN IF NOT EXISTS git_url TEXT,
    ADD COLUMN IF NOT EXISTS git_ref TEXT;
